### PR TITLE
Redstone control

### PR DESCRIPTION
**Pull request by x-j0nnay-x**
This adds Control of the block with redstone, to shut them off with out removing the capture mob

### CODE REVIEW

**Comment by MarkusBordihn** [comment]
Thanks for the PR. I already started implementing this feature but more inline with other mods which has a small red stone toggle switch with the options:

- Ignored (Ignore redstone)
- Normal (Turn on with redstone sigal)
- Inverted (Turn off with redstone signal)

But thanks again for your PR and sorry that I will not be able to merge this PR directly.

**Comment by x-j0nnay-x** [comment]
Okay well at least I’ve learned how to do redstone stuff for my own mod. Just really needed it for my server so they turn off once full using laser io. Glad to hear

**Comment by MarkusBordihn** [comment]
There was some more work to do, but I implemented a redstone mode toggle in the UI for 1.20.1 like:
image

I also mentioned you in the change log for your great help. Thanks.

**Comment by x-j0nnay-x** [comment]
Yeah that is way better looking and more well rounded than my newly learned restore control with block stats lol. And thanks that means a lot I would enjoy helping out as much as I can I really enjoy this mod saves ticks on my server and computers

**Pull request closed without merging**
